### PR TITLE
fix(chains): remove old gemini networks

### LINKED ISSUE #319: Remove gemini 3d and gemini 3a since those networks backends where removed
We need to remove gemini 3a and 3f networks because it was explained by DevOps team that those networks backends where removed.

### PR DESCRIPTION
**Pull request by natachadelarosa**
close #319

### CODE REVIEW

**Review by DaMandal0rian — APPROVED** [review]

File: client/src/gql/index.ts [hunk 1]
```diff
@@ -1,2 +1,2 @@
-export * from "./gql"
-export * from "./fragment-masking"
\ No newline at end of file
+export * from './gql'
+export * from './fragment-masking'
```
Comment (BrianBelhumeur) [inline client/src/gql/index.ts:2]: Do we have ESLint enforcing quote types?

**Review by BrianBelhumeur — APPROVED** [review]
LGTM!
